// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCount():Promise<number>;

export function Print():Promise<string>;

export function StartStopwatch(arg1:string):Promise<void>;

export function StartTickerLoop(arg1:string,arg2:string):Promise<void>;

export function StopTicker():Promise<void>;
