// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCount() {
  return window['go']['main']['App']['GetCount']();
}

export function Print() {
  return window['go']['main']['App']['Print']();
}

export function StartStopwatch(arg1) {
  return window['go']['main']['App']['StartStopwatch'](arg1);
}

export function StartTickerLoop(arg1, arg2) {
  return window['go']['main']['App']['StartTickerLoop'](arg1, arg2);
}

export function StopTicker() {
  return window['go']['main']['App']['StopTicker']();
}
